import "@material/mwc-icon-button";
import "@material/mwc-icon-button-toggle";
import "@material/mwc-tab";
import "@material/mwc-tab-bar";
import { LitElement, TemplateResult, CSSResultGroup } from "lit-element";
import HanziWriterComponent from "./HanziWriter";
import "./HanziWriter";
import HanziWriter from "hanzi-writer";
export default class HanziQuiz extends LitElement {
    strokesVisible: boolean;
    rating: number;
    pinyin: string;
    english: string;
    hanzi: string;
    hanziWriter: HanziWriter | undefined;
    currentCharacterIndex: number;
    get nextCharacter(): string;
    get isWordCompleted(): boolean;
    get hanziWriterComponent(): HanziWriterComponent;
    firstUpdated(): Promise<void>;
    startQuiz(): void;
    fixTabBarMinWidth(): void;
    connectedCallback(): void;
    onVisibilityButtonTapped(e: CustomEvent): void;
    revealStrokes(): void;
    hideStrokes(): void;
    onEraserButtonClick(): void;
    onMistake(): void;
    onComplete(): void;
    ratingButtonClicked(e: CustomEvent): void;
    revealCharacters(hanzi: string, currentCharacterIndex: number): string;
    static get styles(): CSSResultGroup;
    render(): TemplateResult;
}
